version: '3.4'

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --workers 2 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/app/
    ports:
      - 8000:8000
    sysctls:
      net.core.somaxconn: 1024
